export type FinancialDomainErrorCode = "VALIDATION_FAILED" | "REFERENCE_NOT_FOUND" | "DUPLICATE_RECORD" | "BUDGET_VERSION_CONFLICT" | "RECURRING_EFFECTIVE_MONTH_ALREADY_MATERIALIZED" | "RECURRING_EFFECTIVE_MONTH_IN_PAST" | "RECURRING_NO_OP_CHANGE" | "RECURRING_VERSION_ALREADY_MATERIALIZED" | "RECURRING_VERSION_CONFLICT" | "RECURRING_CHANGE_ALREADY_SCHEDULED" | "RECURRING_SCHEDULE_ALREADY_MATERIALIZED" | "RECURRING_SCHEDULE_MUST_BE_CANCELED" | "RECURRING_AUTHORITY_INVALID" | "RECURRING_SOURCE_NOT_FOUND" | "RECURRING_PROPAGATION_CONFLICT" | "RECURRING_FUTURE_VERSION_ALREADY_MATERIALIZED" | "RECURRING_NO_TEMPLATE_CHANGES"

export class FinancialDomainError extends Error {
  constructor(public readonly code: FinancialDomainErrorCode, message: string = code, public readonly details: { field: string; message: string }[] = []) {
    super(message)
    this.name = "FinancialDomainError"
  }
}
