import type { Card, Context, Fund as LegacyFund, MonthCloseoutResponse, RecurringExpense, SavingsPlanResponse, Tag, Transaction, TransactionsPage } from "../../api/types"
import { formatMoneyCents } from "./money"
import { filterTransactions, paginateTransactions, transactionSummary, type TransactionFilter } from "./transactions"
import { ledgerBalance, orderedFunds, type Fund, type FundLedgerEntry } from "./funds"
import type { RehydratedFinancialState } from "../../privacy/encrypted-authority/rehydrate"
import type { TransactionRecord } from "./types"

export interface TransactionListItemVM { id: string; date: string; expense: string; amount: string; category: TransactionRecord["category"]; isSplit: boolean; notes: string | null; source: TransactionRecord["source"]; recurringExpenseId: string | null; tag: Tag; context: Context | null; card: Card | null }
export interface TransactionSummaryVM { totalSpent: string; count: number; average: string; splitCount: number }
export interface TransactionsVM { items: TransactionListItemVM[]; page: number; pageSize: number; totalItems: number; summary: TransactionSummaryVM }

export interface FundVM { id: string; name: string; fundType: string; goalAmount: string | null; status: "active" | "archived"; sortOrder: number; balance: string; remaining: string | null; isGoalMet: boolean }
export interface FundActivityVM { id: string; fundId: string; date: string; type: string; direction: "in" | "out"; amount: string; sourceType: string; sourceTransactionId: string | null; sourceCloseoutId: string | null; isVoided: boolean }
export interface RecurringItemVM { id: string; seriesId: string; expense: string; amount: string; category: TransactionRecord["category"]; billingType: "day_of_month" | "last_day"; billingDay: number | null; projectedDate: string; startsMonth: string; endsMonth: string | null; isActive: boolean; generatedForMonth: boolean }
export interface SavingsPlanVM { month: string; status: string; hasPlan: boolean; savedAmount: string; remainingToSave: string; funds: Array<{ fundId: string; fundName: string; plannedAmount: string; progressAmount: string; goalMet: boolean }> }
export interface CloseoutVM { month: string; status: string; resultType: string | null; surplusAmount: string; deficitAmount: string; allocations: Array<{ id: string; fundId: string | null; label: string | null; amount: string; allocationType: string }> }
export interface CsvImportVM { status: string; totalRows: number; validRows: number; importedRows: number; duplicateRows: number; invalidRows: number; skippedRows: number; errors: Array<{ row: number; field: string | null; message: string }> }

const emptyTag = (id: string | null): Tag => ({ id: id ?? "", name: "", icon_key: null })
const emptyCard = (id: string | null): Card | null => id ? { id, name: "", is_favorite: false } : null
const referenceTail = (value: string) => value.trim().split(":").pop() ?? value.trim()
const sameReferenceId = (left: string, right: string) => left.trim() === right.trim() || referenceTail(left) === referenceTail(right) || left.trim().toLocaleLowerCase() === right.trim().toLocaleLowerCase() || (Number.isFinite(Number(left)) && Number.isFinite(Number(right)) && Number(left) === Number(right))
function tagFromState(state: RehydratedFinancialState, id: string | null): Tag { const item = id == null ? null : state.tags.find((candidate) => sameReferenceId(candidate.id, id) || candidate.name.trim().toLocaleLowerCase() === id.trim().toLocaleLowerCase()); return item ? { id: id ?? item.id, name: item.name, icon_key: item.iconKey } : emptyTag(id) }
function contextFromState(state: RehydratedFinancialState, id: string | null): Context | null { const item = id == null ? null : state.contexts.find((candidate) => sameReferenceId(candidate.id, id) || candidate.name.trim().toLocaleLowerCase() === id.trim().toLocaleLowerCase()); return item ? { id: id ?? item.id, name: item.name, icon_key: item.iconKey } : id ? { id, name: "", icon_key: null } : null }
function cardFromState(state: RehydratedFinancialState, id: string | null): Card | null { const item = id == null ? null : state.cards.find((candidate) => sameReferenceId(candidate.id, id) || candidate.name.trim().toLocaleLowerCase() === id.trim().toLocaleLowerCase()); return item ? { id: id ?? item.id, name: item.name, is_favorite: item.isFavorite } : emptyCard(id) }

export function transactionVM(transaction: Transaction): TransactionListItemVM { return { id: transaction.id, date: transaction.date, expense: transaction.expense, amount: transaction.amount, category: transaction.category, isSplit: transaction.is_split, notes: transaction.notes, source: transaction.source, recurringExpenseId: transaction.recurring_expense_id, tag: transaction.tag, context: transaction.context, card: transaction.card } }
export function transactionsVMFromLegacy(page: { items: Transaction[]; page: number; page_size: number; total_items: number; summary: { total_spent: string; count: number; avg_transaction: string; split_count: number } }): TransactionsVM { return { items: page.items.map(transactionVM), page: page.page, pageSize: page.page_size, totalItems: page.total_items, summary: { totalSpent: page.summary.total_spent, count: page.summary.count, average: page.summary.avg_transaction, splitCount: page.summary.split_count } } }

function internalTransactionVM(state: RehydratedFinancialState, record: TransactionRecord): TransactionListItemVM { return { id: record.id, date: record.date, expense: record.expense, amount: formatMoneyCents(record.amountCents), category: record.category, isSplit: record.isSplit, notes: record.notes, source: record.source, recurringExpenseId: record.recurringExpenseId, tag: tagFromState(state, record.tagId), context: contextFromState(state, record.contextId), card: cardFromState(state, record.cardId) } }
export function transactionsVMFromState(state: RehydratedFinancialState, filter: TransactionFilter = {}): TransactionsVM { const page = paginateTransactions(state.transactions, filter); const summary = transactionSummary(state.transactions, filter); return { items: page.items.map((record) => internalTransactionVM(state, record)), page: page.page, pageSize: page.pageSize, totalItems: page.totalItems, summary: { totalSpent: summary.totalSpent, count: summary.count, average: summary.avgTransaction, splitCount: summary.splitCount } } }
export function transactionsPageFromState(state: RehydratedFinancialState, filter: TransactionFilter = {}): TransactionsPage { const page = paginateTransactions(state.transactions, filter); const summary = transactionSummary(state.transactions, filter); return { items: page.items.map((record) => ({ id: record.id, date: record.date, expense: record.expense, amount: formatMoneyCents(record.amountCents), category: record.category, is_split: record.isSplit, notes: record.notes, source: record.source === "import" ? "import" : "manual", recurring_expense_id: record.recurringExpenseId, tag: tagFromState(state, record.tagId), context: contextFromState(state, record.contextId), card: cardFromState(state, record.cardId), created_at: "", updated_at: "" })), page: page.page, page_size: page.pageSize, total_items: page.totalItems, summary: { total_spent: summary.totalSpent, count: summary.count, avg_transaction: summary.avgTransaction, split_count: summary.splitCount } } }
export function taxonomyFromState(state: RehydratedFinancialState) { return { tags: state.tags.map((item) => ({ id: referenceTail(item.id), name: item.name, icon_key: item.iconKey })), contexts: state.contexts.map((item) => ({ id: referenceTail(item.id), name: item.name, icon_key: item.iconKey })), cards: state.cards.map((item) => ({ id: referenceTail(item.id), name: item.name, is_favorite: item.isFavorite })) } }

export function fundVMFromLegacy(fund: LegacyFund): FundVM { return { id: fund.id, name: fund.name, fundType: fund.fund_type, goalAmount: fund.goal_amount, status: fund.status, sortOrder: fund.sort_order, balance: fund.current_balance, remaining: fund.remaining_amount, isGoalMet: fund.is_goal_met } }
export function fundVMFromState(fund: Fund, entries: FundLedgerEntry[]): FundVM { const balance = ledgerBalance(entries, fund.id); return { id: fund.id, name: fund.name, fundType: fund.fundType, goalAmount: fund.goalAmountCents === null ? null : formatMoneyCents(fund.goalAmountCents), status: fund.status, sortOrder: fund.sortOrder, balance: formatMoneyCents(balance), remaining: fund.goalAmountCents === null ? null : formatMoneyCents(Math.max(0, fund.goalAmountCents - balance)), isGoalMet: fund.goalAmountCents !== null && balance >= fund.goalAmountCents } }
export function fundsVMFromState(funds: Fund[], entries: FundLedgerEntry[]): FundVM[] { return orderedFunds(funds).map((fund) => fundVMFromState(fund, entries)) }

export function recurringVMFromLegacy(item: RecurringExpense): RecurringItemVM { return { id: item.id, seriesId: item.series_id, expense: item.expense, amount: item.amount, category: item.category, billingType: item.billing_type, billingDay: item.billing_day, projectedDate: item.projected_date_for_month, startsMonth: item.starts_month, endsMonth: item.ends_month, isActive: item.is_active, generatedForMonth: item.generated_for_month } }
export function recurringVMFromState(data: Record<string, unknown>): RecurringItemVM { return { id: String(data.id ?? ""), seriesId: String(data.series_id ?? data.recurring_expense_id ?? ""), expense: String(data.expense ?? ""), amount: formatMoneyCents(Number(data.amount_cents ?? 0)), category: String(data.category ?? "needs") as TransactionRecord["category"], billingType: String(data.billing_type ?? "day_of_month") as RecurringItemVM["billingType"], billingDay: data.billing_day == null ? null : Number(data.billing_day), projectedDate: String(data.projected_date_for_month ?? data.due_date ?? ""), startsMonth: String(data.starts_month ?? ""), endsMonth: data.ends_month == null ? null : String(data.ends_month), isActive: data.is_active !== false, generatedForMonth: Boolean(data.generated_for_month) } }

export function savingsVMFromLegacy(plan: SavingsPlanResponse): SavingsPlanVM { return { month: plan.month, status: plan.status, hasPlan: plan.has_plan, savedAmount: plan.summary.saved_amount, remainingToSave: plan.summary.remaining_to_save, funds: plan.funds.map((item) => ({ fundId: item.fund.id, fundName: item.fund.name, plannedAmount: item.planned_amount, progressAmount: item.progress_amount, goalMet: item.pace.status === "goal_met" })) } }
export function closeoutVMFromLegacy(response: MonthCloseoutResponse): CloseoutVM { const closeout = response.closeout; return { month: response.month, status: response.status, resultType: closeout?.result_type ?? response.computed?.result_type ?? null, surplusAmount: closeout?.surplus_amount ?? response.computed?.surplus_amount ?? "0.00", deficitAmount: closeout?.deficit_amount ?? response.computed?.deficit_amount ?? "0.00", allocations: (closeout?.allocations ?? []).map((item) => ({ id: item.id, fundId: item.fund_id, label: item.label, amount: item.amount, allocationType: item.allocation_type })) } }
export function csvVMFromLegacy(result: { status: string; total_rows: number; valid_rows: number; imported_rows: number; duplicate_rows: number; invalid_rows: number; skipped_rows: number; errors: Array<{ row: number; field: string | null; message: string }> }): CsvImportVM { return { status: result.status, totalRows: result.total_rows, validRows: result.valid_rows, importedRows: result.imported_rows, duplicateRows: result.duplicate_rows, invalidRows: result.invalid_rows, skippedRows: result.skipped_rows, errors: result.errors } }
