import type { FundDetail, FundEntry, FundListItem } from "@/lib/api/types"
import type { FundGroup, FundPresentationState } from "./fund-types"
import { parseDisplayMoney } from "@/lib/domain/financial/money"
import { getMonthDateRange, getCurrentMonthKey, toIsoDate } from "@/lib/date-filters"

export function parseAmount(value: string | null | undefined): number { return parseDisplayMoney(value) }
export function moneyToCents(value: string | number | null | undefined): number { return Math.round(parseDisplayMoney(value) * 100) }
export function numberLabel(value: number, singular: string, plural?: string): string { return String(value) + " " + (value === 1 ? singular : plural ?? singular + "s") }
export function stateCountLabel(value: number, singular: string, plural?: string): string | null { return value > 0 ? numberLabel(value, singular, plural) : null }
export function getFundPresentationState(fund: FundListItem): FundPresentationState { if (fund.goal_amount === null) return "open_ended"; const balance = moneyToCents(fund.current_balance); const goal = moneyToCents(fund.goal_amount); return balance <= 0 ? "not_started" : balance >= goal ? "goal_reached" : "in_progress" }
export function sortWorkingFunds(funds: FundListItem[]): FundListItem[] { return funds.map((fund, index) => ({ fund, index })).sort((a, b) => { const left = a.fund.target_month; const right = b.fund.target_month; if (left && right && left !== right) return left.localeCompare(right); if (left && !right) return -1; if (!left && right) return 1; return a.index - b.index }).map(({ fund }) => fund) }
export function groupActiveFunds(funds: FundListItem[]): FundGroup[] { const working: FundListItem[] = []; const open: FundListItem[] = []; const reached: FundListItem[] = []; for (const fund of funds) { const state = getFundPresentationState(fund); if (state === "open_ended") open.push(fund); else if (state === "goal_reached") reached.push(fund); else working.push(fund) } return [{ key: "in_progress", label: "In progress", funds: sortWorkingFunds(working) }, { key: "open_ended", label: "Open-ended", funds: open }, { key: "goal_reached", label: "Goals reached", funds: reached }].filter((group) => group.funds.length > 0) }
export function activeFundStateSummary(funds: FundListItem[]): string { const counts = funds.reduce((result, fund) => { const state = getFundPresentationState(fund); if (state === "open_ended") result.openEnded++; else if (state === "goal_reached") result.goalsReached++; else result.inProgress++; return result }, { inProgress: 0, openEnded: 0, goalsReached: 0 }); return [stateCountLabel(counts.inProgress, "in progress", "in progress"), stateCountLabel(counts.openEnded, "ongoing", "ongoing"), stateCountLabel(counts.goalsReached, "goal reached", "goals reached")].filter((label): label is string => Boolean(label)).join(" · ") || "0 active" }
export function entryTypeLabel(entry: FundEntry): string { if (entry.source_type === "month_closeout") return "Month closeout"; if (entry.source_type === "transaction") return entry.direction === "in" ? "Savings transaction" : "Transaction-linked use"; if (entry.entry_type === "starting_balance") return "Starting balance"; if (entry.entry_type === "adjustment") return "Adjustment"; return entry.direction === "in" ? "Added money" : "Used money" }
export function fundProgressWidth(percent: string | null): string { return String(Math.max(0, Math.min(parseAmount(percent), 100))) + "%" }
export function hasPositiveAmount(value: string | number | null | undefined): boolean { return parseAmount(String(value ?? "")) > 0 }
export function canEditEntry(entry: FundEntry): boolean { return entry.source_type === "manual" || entry.source_type === "starting_balance" || entry.source_type === "correction" }
export function buildBalanceBreakdownRows(fund: FundDetail, entries: FundEntry[]) { const manual = entries.filter((entry) => entry.source_type === "manual" && entry.direction === "in").reduce((sum, entry) => sum + parseAmount(entry.amount), 0); const linked = parseAmount(fund.source_breakdown.transaction); const withdrawals = entries.filter((entry) => entry.direction === "out").reduce((sum, entry) => sum + parseAmount(entry.amount), 0); return [{ label: "Starting balance", amount: parseAmount(fund.source_breakdown.starting_balance) }, { label: "Contributions", amount: manual + linked }, { label: "Withdrawals", amount: -withdrawals }, { label: "Month closeouts", amount: parseAmount(fund.source_breakdown.month_closeout) }, { label: "Corrections", amount: parseAmount(fund.source_breakdown.correction) }].filter((row) => row.amount !== 0) }
export function startOfCurrentMonth(): string { return getMonthDateRange(getCurrentMonthKey())?.date_from ?? toIsoDate(new Date()) }
export function endOfCurrentMonth(): string { return getMonthDateRange(getCurrentMonthKey())?.date_to ?? toIsoDate(new Date()) }
